/**
 * UpCommander Index Connector
 *
 * Reads .codebase-index/ tree files (generated by scripts/generate-codebase-index-tree.ts)
 * and returns formatted context strings for injection into worker system prompts.
 *
 * L0 = top-level branches (~2K tokens) — for contract_generator
 * L1 = sub-branches with exports (~8K tokens) — for implementer/reviewer/solo
 * L2 = full file signatures — only when focusPaths narrows to ≤5 files
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import { homedir } from 'node:os';
import type { WorkerRecipe } from '../workers/types';

// ---------------------------------------------------------------------------
// Types (exported for use by recipe-runner and cli)
// ---------------------------------------------------------------------------

export interface IndexContext {
  level: 'L0' | 'L1' | 'L2';
  text: string;
  tokenEstimate: number;
}

export interface ResolvedSystemPrompt {
  text: string;
  tokenEstimate: number;
}

// ---------------------------------------------------------------------------
// Raw index shapes (from generate-codebase-index-tree.ts)
// ---------------------------------------------------------------------------

interface DirNodeRef {
  name: string;
  slug: string;
  purpose?: string;
  file_count: number;
  line_count: number;
  depth: number;
}

interface FileNode {
  type: 'file';
  name: string;
  lines: number;
  exports: string[];
  signatures: string[];
  purpose?: string;
}

interface DirNode {
  type: 'dir';
  name: string;
  path: string;
  slug: string;
  purpose?: string;
  file_count: number;
  line_count: number;
  depth: number;
  children_dirs: DirNodeRef[];
  children_files: FileNode[];
}

interface TreeIndex {
  generated: string;
  root: string;
  total_dirs: number;
  total_files: number;
  total_lines: number;
  top_branches: DirNodeRef[];
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function indexDir(repoPath: string): string {
  return path.join(repoPath, '.codebase-index');
}

function readJson<T>(filePath: string): T | null {
  if (!fs.existsSync(filePath)) return null;
  try {
    return JSON.parse(fs.readFileSync(filePath, 'utf-8')) as T;
  } catch {
    return null;
  }
}

function roughTokens(text: string): number {
  return Math.ceil(text.length / 4);
}

function fmtBranch(b: DirNodeRef): string {
  const purpose = b.purpose ? ` — ${b.purpose}` : '';
  return `• ${b.name}${purpose} (${b.file_count} files, ${b.line_count} lines)`;
}

// ---------------------------------------------------------------------------
// L0: top-level branches only (~1-3K tokens)
// ---------------------------------------------------------------------------

function buildL0(repoPath: string): string {
  const root = readJson<TreeIndex>(path.join(indexDir(repoPath), 'index.json'));
  if (!root) return '[codebase-index not found — run: npx tsx scripts/generate-codebase-index-tree.ts]';

  const lines: string[] = [
    '=== CODEBASE INDEX L0 ===',
    `[generated: ${root.generated}]`,
    `Total: ${root.total_dirs} dirs, ${root.total_files} files, ${root.total_lines.toLocaleString()} lines`,
    '',
    'TOP BRANCHES:',
  ];

  for (const b of root.top_branches) {
    lines.push(fmtBranch(b));
  }

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// L1: medium branches — expands each top-branch one level deep
// ---------------------------------------------------------------------------

function buildL1(repoPath: string, focusPaths?: string[]): string {
  const root = readJson<TreeIndex>(path.join(indexDir(repoPath), 'index.json'));
  if (!root) return buildL0(repoPath);

  const lines: string[] = [
    '=== CODEBASE INDEX L1 ===',
    `[generated: ${root.generated}]`,
    `Total: ${root.total_dirs} dirs, ${root.total_files} files`,
    '',
  ];

  for (const branch of root.top_branches) {
    if (focusPaths && focusPaths.length > 0) {
      const matches = focusPaths.some(fp =>
        branch.name.includes(fp) || fp.includes(branch.name)
      );
      if (!matches) {
        lines.push(fmtBranch(branch));
        continue;
      }
    }

    const node = readJson<DirNode>(path.join(indexDir(repoPath), `${branch.slug}.json`));
    if (!node) {
      lines.push(fmtBranch(branch));
      continue;
    }

    const purposeStr = node.purpose ? ` — ${node.purpose}` : '';
    lines.push(`\n── ${branch.name}${purposeStr} (${node.file_count} files)`);

    if (node.children_dirs.length > 0) {
      lines.push('  SUB-MODULES:');
      for (const child of node.children_dirs) {
        // Read child node for exports
        const childNode = readJson<DirNode>(path.join(indexDir(repoPath), `${child.slug}.json`));
        const exportList = childNode
          ? childNode.children_files.flatMap(f => f.exports).slice(0, 8).join(', ')
          : '';
        const purposeStr2 = child.purpose ? ` — ${child.purpose}` : '';
        const exportsStr = exportList ? `\n    exports: ${exportList}` : '';
        lines.push(`  • ${child.name}/${purposeStr2} (${child.file_count} files, ${child.line_count} lines)${exportsStr}`);
      }
    }

    if (node.children_files.length > 0) {
      lines.push('  FILES:');
      for (const f of node.children_files) {
        const purposeStr3 = f.purpose ? ` — ${f.purpose}` : '';
        const exportsStr = f.exports.length > 0 ? ` | exports: ${f.exports.slice(0, 6).join(', ')}` : '';
        lines.push(`  • ${f.name}${purposeStr3}${exportsStr}`);
      }
    }
  }

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// L2: full signatures for specific paths
// ---------------------------------------------------------------------------

function buildL2(repoPath: string, focusPaths: string[]): string {
  if (focusPaths.length === 0) return buildL1(repoPath);

  const lines: string[] = [
    '=== CODEBASE INDEX L2 ===',
    `[focus: ${focusPaths.join(', ')}]`,
    '',
  ];

  // Walk the index tree to find nodes matching focusPaths
  const idxDir = indexDir(repoPath);
  if (!fs.existsSync(idxDir)) return buildL1(repoPath, focusPaths);

  const allJsons = fs.readdirSync(idxDir).filter(f => f.endsWith('.json') && f !== 'index.json');

  for (const jsonFile of allJsons) {
    const node = readJson<DirNode>(path.join(idxDir, jsonFile));
    if (!node) continue;

    const matches = focusPaths.some(fp =>
      node.path.includes(fp) || fp.includes(node.path)
    );
    if (!matches) continue;

    lines.push(`── ${node.path} (${node.file_count} files)`);

    for (const f of node.children_files) {
      const purposeStr = f.purpose ? ` — ${f.purpose}` : '';
      lines.push(`  ${f.name}${purposeStr}`);
      if (f.signatures.length > 0) {
        for (const sig of f.signatures) {
          lines.push(`    fn ${sig}`);
        }
      } else if (f.exports.length > 0) {
        lines.push(`    exports: ${f.exports.join(', ')}`);
      }
    }
    lines.push('');
  }

  return lines.join('\n') || buildL1(repoPath, focusPaths);
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Load the codebase index at a given level and return a formatted context string.
 */
export function loadIndexContext(
  repoPath: string,
  level: 'L0' | 'L1' | 'L2',
  focusPaths?: string[]
): IndexContext {
  let text: string;

  switch (level) {
    case 'L0': text = buildL0(repoPath); break;
    case 'L1': text = buildL1(repoPath, focusPaths); break;
    case 'L2': text = buildL2(repoPath, focusPaths ?? []); break;
    default:   text = buildL0(repoPath);
  }

  return { level, text, tokenEstimate: roughTokens(text) };
}

/**
 * Assemble a complete system prompt from a WorkerRecipe.
 * Resolves karpathy, index, contract, and raw parts in order.
 */
export async function buildSystemPrompt(
  recipe: WorkerRecipe,
  repoPath: string,
  extras?: {
    contractPath?: string;
    karpathyPath?: string;
    focusPaths?: string[];
  }
): Promise<ResolvedSystemPrompt> {
  const parts: string[] = [];

  for (const part of recipe.system_prompt_parts) {
    switch (part.type) {
      case 'karpathy': {
        const kPath = extras?.karpathyPath
          ?? path.join(homedir(), '.claude', 'library', 'karpathy-skills.md');
        if (fs.existsSync(kPath)) {
          parts.push(fs.readFileSync(kPath, 'utf-8'));
        }
        // Graceful skip if absent — not a hard requirement for OSS users
        break;
      }

      case 'index': {
        const level = (part.level as 'L0' | 'L1' | 'L2') ?? 'L1';
        const ctx = loadIndexContext(repoPath, level, extras?.focusPaths);
        parts.push(ctx.text);
        break;
      }

      case 'contract': {
        const contractPath = extras?.contractPath
          ?? path.join(repoPath, '.claude-coord', 'CONTRACT.md');
        if (fs.existsSync(contractPath)) {
          parts.push(`=== CONTRACT.md ===\n${fs.readFileSync(contractPath, 'utf-8')}`);
        }
        break;
      }

      case 'raw': {
        parts.push(part.content);
        break;
      }
    }
  }

  const text = parts.filter(Boolean).join('\n\n---\n\n');
  return { text, tokenEstimate: roughTokens(text) };
}
